spring:
    profiles: prod
    jpa.hibernate.ddl-auto: validate

server.port: 8080

logging:
    level:
        org.jboss.resteasy.springmvc.ResteasyHandlerMapping: ERROR
        org.meruvian.yama: DEBUG

rest:
    login_form: /
    clients:
        - id: yama
          secret: yamameruvianorgsecret
          redirect: /

# database
db:
    url: jdbc:mysql://localhost:3306/yama2
    driver: com.mysql.jdbc.Driver
    datasource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: root
    password: 
    max_pool_size: 100
    test_query: SELECT 1
    run_migration: true
    
# upload
upload:
    path:
        base: /tmp/yama
        profile_pic: /profile_pic

# default
default:
    role: USER
    site: DEFAULT
    profile_pic:
        path: /images/default_profile.gif
        content_type: image/gif

# social
social:
    mervid:
        active: true
        appId: 69718777-b3f5-4d53-be85-fde18528ea5f
        appSecret: j/jygXp6JczO5pIJ/PXNn/x9iFrOp7pibJ6SBjDeA87R1Fj+BaP/9rfqUTT9LGJr
        redirectUri: http://localhost:8080/login/social/mervid/callback
        scope: read write
    facebook:
        active: true
        appId: 645592102187632
        appSecret: 88ee3cdd671536f452879042a85ae780
        redirectUri: http://localhost:8080/login/social/facebook/callback
        scope: email,public_profile,user_friends
    google:
        active: true
        appId: 712009183750-9102gsasvgb7nklms2opuo3oknk2cgm1.apps.googleusercontent.com
        appSecret: tSN5B1QfGS0JIq69vHdNmRzt
        redirectUri: http://localhost:8080/login/social/google/callback
        scope: https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email
    linkedin:
        active: true
        appId: 75b6ivkawa0der
        appSecret: WotBifIF7XIWNkM0
        redirectUri: http://localhost:8080/login/social/linkedin/callback
        scope: r_basicprofile r_emailaddress
    github:
        active: true
        appId: c49df12b2dce950b4882
        appSecret: ee66e74b67817eb63e96e6d08a37ab055c3f3402
        redirectUri: http://localhost:8080/login/social/github/callback
        scope: user

# email
email:
    host: localhost
    port: 25
    username: 
    password: 
    from_email: yama@localhost
    from_alias: Yama
    ssl: false
    tls: false

# recaptcha
recaptcha:
    active: true
    public_key: 6LdoBdESAAAAAHXfBTxpdn0gdlo3Ov3oLaOf4Jeh
    private_key: 6LdoBdESAAAAAKF_QC5MSRVwLbXvozXLjljUFEsG
    include_noscript: false